### ISSUE TITLE
How/where does istio gets installed?

### ISSUE THREAD

**Issue by vikas027** [ruzickap/k8s-flagger-istio-flux#10]
Hey @ruzickap ,

First of all, thanks for the awesome writeup. I went through the repo and the video, but could not find the place where you have installed Istio.

Have you used istioctl or istio helm to install Istio?

**Comment by ruzickap** [comment]
Hello.

The Istio installation (+ many other components) are included in the Terraform code: https://github.com/ruzickap/k8s-flagger-istio-flux/blob/master/terraform/modules/k8s_initial_config/istio.tf

I do have the Istio installation written here for example: https://ruzickap.github.io/k8s-knative-gitlab-harbor/part-03/#install-istio

Anyway I recommend you to follow the official way of installing Istio written on the [istio.io](https://istio.io/) and using the version 1.4.x (latest stable).

The answer to your question is that I'm using Terraform Helm chart module to install Istio (1.3.0) in my example.

**Comment by vikas027** [comment]
Thanks for the detailed info @ruzickap .
